## Time-stamp: <2017-06-25 10:52:10 vk>
## -*- coding: utf-8 -*-
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/

* tweets2org.py

This python script converts the [[https://blog.twitter.com/2012/your-twitter-archive][Twitter export files]] ([[https://en.wikipedia.org/wiki/Json][JSON format]])
into an [[http://orgmode.org][Org-mode]] file.

Note: If you are using [[https://github.com/novoid/Memacs][Memacs]] to get stuff from various sources into
your Org-mode you might try [[https://github.com/novoid/Memacs/blob/master/docs/memacs_twitter.org][its Twitter module]] instead of this method
here. However, it requires you to give Twitter your phone number.
Therefore, I do prefer the method described here.

Short URLs are replaced with their expanded URLs, many things are turned
into meaningful links where possible.

1. Download your [[https://blog.twitter.com/2012/your-twitter-archive][Twitter export files]]
2. Unpack the ZIP file
3. Convert the data using this script (see below)

Example usage:
: tweets2org.py -o tweets.org ~/Twitter_export_USER.json/*.js --add-to-time-stamps="+1"
... converts the Twitter export files and adds one hour to time stamps

For all command line options, please call: ~tweets2org.py --help~

- *Target group*: users who are using Twitter and Emacs Org-mode
- Hosted on github: https://github.com/novoid/twitter-json_to_orgmode

If you don't get emails with the download archive after requesting it,
you [[http://karl-voit.at/2017/06/25/twitter-archive/][might be interested to read about how to fix that]].

* Contribute!

I am looking for your ideas!

If you want to contribute to this cool project, please fork and
contribute!


* Local Variables                                                  :noexport:
# Local Variables:
# mode: auto-fill
# mode: flyspell
# eval: (ispell-change-dictionary "en_US")
# End:
